return {
  -- {
  --   "shortcuts/no-neck-pain.nvim",
  --   version = "*",
  --   config = function()
  --     require("no-neck-pain").setup {
  --       width = 30,
  --       buffers = {
  --         right = { enabled = false }, -- left padding only
  --         -- чисто визуально, чтобы не было "~" в пустом буфере
  --         wo = { fillchars = "eob: " },
  --
  --         -- если хочешь “полезное” вместо декоративного:
  --         -- scratchPad = { enabled = true, location = "~/Documents/" },
  --         -- bo = { filetype = "md" },
  --       },
  --       autocmds = {
  --         enableOnVimEnter = true,
  --       },
  --     }
  --   end,
  -- },
}
